In [1]:
import pandas as pd

In [6]:
nameslist3 = pd.read_csv('nameslist3.csv')
nameslist4 = pd.read_csv('nameslist4.csv')
missing_name_list_update = pd.read_csv('missing_name_list_update.csv')

In [21]:
missing_name_list_update = missing_name_list_update[['name', 'zip']]

In [28]:
merged_df_step_1 = missing_name_list_update.merge(nameslist3, left_on='name', right_on='name')
merged_df_step_2 = missing_name_list_update.merge(nameslist4, left_on='name', right_on='name')
merged_df = pd.concat([merged_df_step_1, merged_df_step_2])
# merged_df.to_csv('extra_fips.csv')
merged_df

C:\Users\marti\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

,FIPS,Unnamed: 0,X,county,fips,name,state,state2,stateshort,zip,zip.x,zip.y
0,NaN,6664,NaN,Ocean,34029,Alan Floria,NaN,NaN,NJ,872,NaN,NaN
1,NaN,4286,NaN,Iberia,22045,Edwin S Patout,NaN,NaN,LA,70561,NaN,NaN
2,NaN,7006,NaN,Nassau,36059,Gregory V Hand,NaN,NaN,NY,9263,NaN,NaN
3,NaN,2457,NaN,Pinellas,12103,"John M. Elias, P.A.",NaN,NaN,FL,34616,NaN,NaN
4,NaN,7584,NaN,Westchester,36119,"Kevin J. Quaranta, Esq.",NaN,NaN,NY,10569,NaN,NaN
5,NaN,4815,NaN,Middlesex,25017,Maria A. Ioannou-Begin,NaN,NaN,MA,170,NaN,NaN
6,NaN,2452,NaN,Pinellas,12103,Michael G Brady,NaN,NaN,FL,34648,NaN,NaN
7,NaN,7928,NaN,Cuyahoga,39035,Paul Anthony Caimi,NaN,NaN,OH,44002,NaN,NaN
8,NaN,2939,NaN,Gwinnett,13135,Randall Scott Estes,NaN,NaN,GA,30245,NaN,NaN
9,NaN,10570,NaN,Arlington,51013,Robert L. Berkebile,NaN,NaN,DC,20000,NaN,NaN
10,NaN,10731,NaN,Manassas,51683,Thomas E Burks,NaN,NaN,VA,22110,NaN,NaN
0,13051.0,1,0.0,NaN,no data,Allan T Downen,no data,GA,NaN,30050,30050.0,30050.0
1,26125.0,2,1.0,NaN,no data,Ari Kresch,no data,MI,NaN,24100,24100.0,24100.0
2,48453.0,3,2.0,NaN,no data,Clay Kutch,no data,TX,NaN,78707,78707.0,78707.0
3,29165.0,4,3.0,NaN,no data,D. Bryant King III.,no data,MO,NaN,64135,64135.0,64135.0
4,34039.0,5,4.0,NaN,no data,Edmund S Bloom Jr.,no data,NY,NaN,9842,9842.0,9842.0
5,NaN,6,5.0,NaN,no data,Edward L. Barry,no data,VA,NaN,820,820.0,820.0
6,47187.0,7,6.0,NaN,no data,James S Bramell,no data,TN,NaN,32027,32027.0,32027.0
7,18097.0,8,7.0,NaN,no data,Jeff D. Oliphant,no data,IN,NaN,40960,40960.0,40960.0
8,6059.0,9,8.0,NaN,no data,Joseph C. Rosenblit,no data,CA,NaN,96275,96275.0,96275.0
9,36061.0,11,9.0,NaN,no data,Kevin G Boisvert,no data,NY,NaN,1000,1000.0,1000.0
10,35001.0,12,10.0,NaN,no data,M J Keefe,no data,NM,NaN,87100,87100.0,87100.0
11,25005.0,13,11.0,NaN,no data,Margaret D Xifaras,no data,MA,NaN,2704,2704.0,2704.0
12,NaN,14,12.0,NaN,no data,Mary M Cecil,no data,FL,NaN,34004,34004.0,34004.0
13,22069.0,15,13.0,NaN,no data,Otis Edwin Dunahoe Jr,no data,LA,NaN,71547,71547.0,71547.0
14,12103.0,16,14.0,NaN,no data,Paul R Hull,no data,FL,NaN,34616,34616.0,34616.0
15,25001.0,17,15.0,NaN,no data,Paula M. Barbosa,no data,MA,NaN,2450,2450.0,2450.0
16,51683.0,18,16.0,NaN,no data,Richard F Wheeler,no data,VA,NaN,22110,22110.0,22110.0
17,25025.0,19,17.0,NaN,no data,"Scott D. Goldberg, Esq.",no data,MA,NaN,211,211.0,211.0
18,34039.0,20,18.0,NaN,no data,Thomas C Jaster,no data,NY,NaN,9459,9459.0,9459.0
19,13135.0,21,19.0,NaN,no data,Thomas Michael Farrell,no data,GA,NaN,30245,30245.0,30245.0
20,13135.0,22,20.0,NaN,no data,"Walter E Manuel Jr., P.C.",no data,GA,NaN,30278,30278.0,30278.0

In [31]:
missing_names_no_fips.to_csv('missing_names_fips.csv')

In [29]:
zip_to_fips = pd.read_csv('ZIP-COUNTY-FIPS_2017-06.csv')

In [33]:
state_codes = {
    'WA': '53', 'DE': '10', 'DC': '11', 'WI': '55', 'WV': '54', 'HI': '15',
    'FL': '12', 'WY': '56', 'PR': '72', 'NJ': '34', 'NM': '35', 'TX': '48',
    'LA': '22', 'NC': '37', 'ND': '38', 'NE': '31', 'TN': '47', 'NY': '36',
    'PA': '42', 'AK': '02', 'NV': '32', 'NH': '33', 'VA': '51', 'CO': '08',
    'CA': '06', 'AL': '01', 'AR': '05', 'VT': '50', 'IL': '17', 'GA': '13',
    'IN': '18', 'IA': '19', 'MA': '25', 'AZ': '04', 'ID': '16', 'CT': '09',
    'ME': '23', 'MD': '24', 'OK': '40', 'OH': '39', 'UT': '49', 'MO': '29',
    'MN': '27', 'MI': '26', 'RI': '44', 'KS': '20', 'MT': '30', 'MS': '28',
    'SC': '45', 'KY': '21', 'OR': '41', 'SD': '46', 'VI': '52'
}

In [34]:
zip_to_fips.replace({"STATE": state_codes})

         ZIP               COUNTYNAME STATE  STCOUNTYFP CLASSFP
0      36003           Autauga County    01        1001      H1
1      36006           Autauga County    01        1001      H1
2      36067           Autauga County    01        1001      H1
3      36066           Autauga County    01        1001      H1
4      36703           Autauga County    01        1001      H1
5      36701           Autauga County    01        1001      H1
6      36091           Autauga County    01        1001      H1
7      36051           Autauga County    01        1001      H1
8      36068           Autauga County    01        1001      H1
9      36008           Autauga County    01        1001      H1
10     36022           Autauga County    01        1001      H1
11     36749           Autauga County    01        1001      H1
12     36758           Autauga County    01        1001      H1
13     36550           Baldwin County    01        1003      H1
14     36551           Baldwin County    01        1003      H1
15     36527           Baldwin County    01        1003      H1
16     36577           Baldwin County    01        1003      H1
17     36559           Baldwin County    01        1003      H1
18     36536           Baldwin County    01        1003      H1
19     36576           Baldwin County    01        1003      H1
20     36579           Baldwin County    01        1003      H1
21     36502           Baldwin County    01        1003      H1
22     36578           Baldwin County    01        1003      H1
23     36533           Baldwin County    01        1003      H1
24     36564           Baldwin County    01        1003      H1
25     36561           Baldwin County    01        1003      H1
26     36580           Baldwin County    01        1003      H1
27     36535           Baldwin County    01        1003      H1
28     36547           Baldwin County    01        1003      H1
29     36549           Baldwin County    01        1003      H1
...      ...                      ...   ...         ...     ...
52859    924  Trujillo Alto Municipio    72       72139      H1
52860    976  Trujillo Alto Municipio    72       72139      H1
52861    957  Trujillo Alto Municipio    72       72139      H1
52862    778  Trujillo Alto Municipio    72       72139      H1
52863    961  Trujillo Alto Municipio    72       72139      H1
52864    962  Trujillo Alto Municipio    72       72139      H1
52865    917  Trujillo Alto Municipio    72       72139      H1
52866    641         Utuado Municipio    72       72141      H1
52867    612         Utuado Municipio    72       72141      H1
52868    611         Utuado Municipio    72       72141      H1
52869    687      Vega Alta Municipio    72       72143      H1
52870    646      Vega Alta Municipio    72       72143      H1
52871    692      Vega Alta Municipio    72       72143      H1
52872    692      Vega Baja Municipio    72       72145      H1
52873    674      Vega Baja Municipio    72       72145      H1
52874    687      Vega Baja Municipio    72       72145      H1
52875    693      Vega Baja Municipio    72       72145      H1
52876    694      Vega Baja Municipio    72       72145      H1
52877    765        Vieques Municipio    72       72147      H1
52878    766       Villalba Municipio    72       72149      H1
52879    720       Villalba Municipio    72       72149      H1
52880    767        Yabucoa Municipio    72       72151      H1
52881    653          Yauco Municipio    72       72153      H1
52882    606          Yauco Municipio    72       72153      H1
52883    698          Yauco Municipio    72       72153      H1
52884    850         St. Croix Island    52       78010      H4
52885    840         St. Croix Island    52       78010      H4
52886    820         St. Croix Island    52       78010      H4
52887    830          St. John Island    52       78020      H4
52888    802        St. Thomas Island    52       78030      H4

[52889 rows x 5 columns]

In [35]:
zip_to_fips.to_csv('zip_to_fips.csv')