In [43]:
import pandas as pd
import string

In [44]:
df = pd.read_csv('name_zip_fips_state_Dec_18_with_missing.csv', dtype = str)
#Add leading zeros to the dataframe for the state and fips columns
df.astype({'fips': 'str'}).dtypes
df['fips'] = df['fips'].str.zfill(3)
df

                            name    zip state fips
0         A Allsbrook Richardson  29574    SC  033
1             A Elizabeth Turner  90503    CA  037
2                    A J Wambach  56557    MN  029
3               A Joseph Guarino   8742    NJ  029
4              A Omotayo Orederu  10302    NY  085
5               A Randolph Comba  61356    IL  011
6             A. Blake MacDonald  55802    MN  137
7            A. Bowdre Banks Jr.  70130    LA  071
8             A. Bryan Tomlinson  19103    PA  101
9      A. Collin Cherry, Esquire  32301    FL  073
10              A. Craig Purcell  11788    NY  103
11                A. David Fawal  35203    AL  073
12                 A. Dawn Hayes  33596    FL  057
13                A. Dwight Hood  39110    MS  089
14              A. Gregory Ramos  37219    TN  037
15              A. Gus Mastracci  32162    FL  069
16                A. Harold Datz  19107    PA  101
17            A. Howard Williams  46601    IN  141
18         A. I. Stacey Williams  70113    LA  071
19             A. J. Balbo, Esq.  31324    GA  029
20                A. Jack Hinton  30305    GA  121
21                A. James Leeds  91316    CA  037
22                  A. Jeff Kemp  77380    TX  339
23                 A. Lance Tonn  59301    MT  017
24                A. Lou Benassi  61603    IL  143
25              A. Mac Martinson  35801    AL  089
26                  A. Major Bey  19130    PA  101
27            A. Mark O Danovich  60601    IL  031
28               A. Michael Nalu  92101    CA  073
29              A. Newton Dilley  49503    MI  081
...                          ...    ...   ...  ...
25981             Gregory V Hand   9263    NY  059
25982        John M. Elias, P.A.  34616    FL  103
25983    Kevin J. Quaranta, Esq.  10569    NY  119
25984     Maria A. Ioannou-Begin    170    MA  017
25985            Michael G Brady  34648    FL  103
25986         Paul Anthony Caimi  44002    OH  035
25987        Randall Scott Estes  30245    GA  135
25988        Robert L. Berkebile  20000    DC  013
25989             Thomas E Burks  22110    VA  683
25990             Allan T Downen  30050    GA  051
25991                 Ari Kresch  24100    MI  125
25992                 Clay Kutch  78707    TX  453
25993        D. Bryant King III.  64135    MO  165
25994         Edmund S Bloom Jr.   9842    NY  039
25995            Edward L. Barry    820    VA  NaN
25996            James S Bramell  32027    TN  187
25997           Jeff D. Oliphant  40960    IN  097
25998        Joseph C. Rosenblit  96275    CA  059
25999           Kevin G Boisvert   1000    NY  061
26000                  M J Keefe  87100    NM  001
26001         Margaret D Xifaras   2704    MA  005
26002               Mary M Cecil  34004    FL  NaN
26003      Otis Edwin Dunahoe Jr  71547    LA  069
26004                Paul R Hull  34616    FL  103
26005           Paula M. Barbosa   2450    MA  001
26006          Richard F Wheeler  22110    VA  683
26007    Scott D. Goldberg, Esq.    211    MA  025
26008            Thomas C Jaster   9459    NY  039
26009     Thomas Michael Farrell  30245    GA  135
26010  Walter E Manuel Jr., P.C.  30278    GA  135

[26011 rows x 4 columns]

In [45]:
name_list = df['name']
last_name_list = []
name_extentions_list = ['jr', 'i', 'ii', 'iii', 'iv', 'v', 'vi', 'sr', 'jd', 'rn', 'bsn', 'cpa', 'cgma', 'ctp', 'mba', 'cma', 'pe', 'esq', '-']
for name in name_list:
    while ',' in name:
        name = name.split(',')[0]
    while ' (' in name:
        name = name.split(' (')[0]
    name = name.split(' ')
    i = -1
    last_name_found = False
    while last_name_found == False:
        if any(name_suf == name[i].lower() for name_suf in name_extentions_list):
            i -= 1
        elif '.' in name[i]:
            i -= 1
        else:
            last_name_list.append(name[i])
            last_name_found = True
last_name_list

['Richardson',
 'Turner',
 'Wambach',
 'Guarino',
 'Orederu',
 'Comba',
 'MacDonald',
 'Banks',
 'Tomlinson',
 'Cherry',
 'Purcell',
 'Fawal',
 'Hayes',
 'Hood',
 'Ramos',
 'Mastracci',
 'Datz',
 'Williams',
 'Williams',
 'Balbo',
 'Hinton',
 'Leeds',
 'Kemp',
 'Tonn',
 'Benassi',
 'Martinson',
 'Bey',
 'Danovich',
 'Nalu',
 'Dilley',
 'Khalil',
 'Gibbs',
 'Spinella',
 'Weissenstein',
 'Lomonaco',
 'Sanders',
 'Friday',
 'Snell',
 'Thomson',
 'Gloeser',
 'Sirna',
 'DeCaro',
 'Janklow',
 'Chase',
 'Tillery',
 'Mattingly',
 'McManes',
 'Hunter',
 'Tauke',
 'James',
 'Lucas',
 'Mander',
 'Angelis',
 'Krolik',
 'Amore',
 'Gregg',
 'Denton',
 'Johnson',
 'Ryan',
 'Felton',
 'Randall',
 'Bundy',
 'Crane',
 'Delgado',
 'Eiesland',
 'Lauter',
 'Salberg',
 'Speck',
 'Wiseley',
 'Glazer',
 'Allison',
 'Garrett',
 'Ginkens',
 'Allen',
 'Broussard',
 'Rolen',
 'Jainchill',
 'House',
 'Kelly',
 'Reed',
 'Woods',
 'Maurice',
 'Sobel',
 'Ritchie',
 'Rodgers',
 'Hicks',
 'Ferguson',
 'Graves',
 'Rapier',
 'Rodenburg',
 'Smith',
 'Watson',
 'Sachs',
 'Jolles',
 'Fenichel',
 'Spears',
 'Richardson',
 'Innabi',
 'Saadiq',
 'Omerhodic',
 'Paul',
 'Orendain',
 'Reyna',
 'Cardenas',
 'Mayers',
 'Saad',
 'Nievod',
 'Kassis',
 'Reingold',
 'Barreto',
 'Studnicki',
 'Brown',
 'Kuenning',
 'Lederman',
 'Riback',
 'Schwartz',
 'Barnett',
 'Loeb',
 'Carlson',
 'Chrzan',
 'Collins',
 'Blechman',
 'Herzog',
 'Young',
 'Davis',
 'Demetri',
 'Bossov',
 'Carr',
 'Schramm',
 'Evans',
 'Flores',
 'Cross',
 'Getson',
 'Hill',
 'Malinowski',
 'Bean',
 'Blank',
 'Curry',
 'Resmini',
 'Soibelman',
 'Tabak',
 'Teller',
 'Wax',
 'Russo',
 'Vernau',
 'Rodd',
 'Brown',
 'Jurach',
 'Stefancic',
 'Malone',
 'Mazonson',
 'Meltsner',
 'Cerbone',
 'Kossayda',
 'Prochaska',
 'Pugh',
 'Glinn',
 'Baker',
 'Bernstein',
 'Hall',
 'Weintraub',
 'Symington',
 'Johnson',
 'Williamson',
 'Trop',
 'Goff',
 'Blackmore',
 'Jacobs',
 'Horan',
 'Lara',
 'Anarado',
 'Levy',
 'Sicheri',
 'Ellis',
 'Dunning',
 'Hunte',
 'Altshuler',
 'Hoosier',
 'Wasko',
 'Meyer',
 'Peguese',
 'Hershey',
 'Villarreal',
 'Pickard',
 'Snelling',
 'Logeman',
 'Burke',
 'Baranoff',
 'Klein',
 'Hahn',
 'Davis',
 'King',
 'Raynor',
 'Petersen',
 'Ribeiro',
 'Cammisa',
 'Reynolds',
 'Su',
 'Dyches',
 'Droughton',
 'Leipprandt',
 'Rabalais',
 'Murphy',
 'Moshaiv',
 'Amer',
 'Iacocca',
 'Carrion',
 'Schallau',
 'Hom',
 'Tamuno',
 'Carrico',
 'Aleksander',
 'Alhadeff',
 'Weber',
 'Fish',
 'Havis',
 'Neurick',
 'Waln',
 'Banov',
 'Bellenger',
 'Miller',
 'Geohagan',
 'Anchell',
 'Betz',
 'Espy',
 'Taylor',
 'Bell',
 'Budman',
 'Henderson',
 'Levine',
 'Watson',
 'Toll',
 'Varner',
 'Smietanski',
 'Floria',
 'Blatnikoff',
 'Greenberg',
 'Ginsberg',
 'Greer',
 'Greenberg',
 'Barbanel',
 'Hunt',
 'Schimmel',
 'Markman',
 'Ominsky',
 'Baldwin',
 'Belsky',
 'Booth',
 'Cohen',
 'Golden',
 'Konigsberg',
 'Nuta',
 'Statman',
 'Braverman',
 'Foxman',
 'Lander',
 'Lerner',
 'Stratton',
 'Foe',
 'Kansas',
 'Kolod',
 'Kreshtool',
 'Mealy',
 'Joseph',
 'Newman',
 'Schwalbe',
 'Sirkin',
 'Whitted',
 'Kraut',
 'Tanenbaum',
 'Tepper',
 'Greenberg',
 'Purdie',
 'Salkow',
 'Wolinsky',
 'Foody',
 'Molina',
 'Molina',
 'Bayham',
 'Dove',
 'Taylor',
 'Pearlman',
 'Davis',
 'Beard',
 'Cochran',
 'Goodman',
 'Lebowitz',
 'LeCours',
 'Levy',
 'Pfaff',
 'Kolodny',
 'Roberts',
 'Rosenberg',
 'Baum',
 'Dambrov',
 'Friedman',
 'Funk',
 'Gold',
 'Levine',
 'Pierce',
 'Miller',
 'Pickel',
 'Silko',
 'Starker',
 'Stegall',
 'Rubin',
 'Sylvester',
 'Johnson',
 'Cohn',
 'Wagner',
 'Medvin',
 'Clements',
 'Henry',
 'Dunisha',
 'Biel',
 'Wolf',
 'Aaron',
 'Mitchell',
 'Dragon',
 'Davies',
 'Desrosiers',
 'Fershing',
 'Hollan',
 'Jones',
 'Moon',
 'Ranum',
 'Maier',
 'Ries',
 'Shamash',
 'Farrah',
 'Hubby',
 'Guadagno',
 'Rescinio',
 'Sreter',
 'Bannon',
 'DeCusati',
 'Fiorella',
 'Slap',
 'Bolet',
 'Saslow',
 'Wheeler',
 'Messer',
 'Pearson',
 'Thiel',
 'Matthews',
 'Lazarus',
 'Salvi',
 'Huff',
 'Chianese',
 'Cornachio',
 'Miller',
 'Berrones',
 'Franco',
 'Guadagno',
 'Virgen',
 'Harrington',
 'Beltrano',
 'Stolte',
 'Hanus',
 'Wisner',
 'Elston',
 'Szwarcsztejn',
 'Fiol',
 'Rodriguez',
 'Days',
 'Strand',
 'Marra',
 'Giribaldi',
 'Lauricella',
 'Omrani',
 'Scheingross',
 'Wallach',
 'Dunn',
 'Elder',
 'Chapman',
 'Cheng',
 'Philippone',
 'Ghibaudo',
 'Goldberg',
 'Sitz',
 'Hanna',
 'Miller',
 'Remick',
 'Kapetan',
 'Rabin',
 'Friedland',
 'Postic',
 'Nocerino',
 'Russell',
 'Wright',
 'Barrera',
 'Begum',
 'Boyd',
 'Crecca',
 'Sklavos',
 'Reichert',
 'Hait',
 'Rozman',
 'Gordon',
 'Jamiolkowski',
 'Kemeny',
 'Smith',
 'Ginsburg',
 'Alfano',
 'Davison',
 'Karasik',
 'Latanision',
 'Levine',
 'Silow',
 'Lumelsky',
 'Dashe',
 'Weinberg',
 'Levay',
 'Cain',
 'Kammer',
 'Simanovsky',
 'Mora',
 'Hull',
 'Schultz',
 'Bonin',
 'Pittas-Giroux',
 'Langella',
 'Mullaney',
 'Sivertson',
 'Langan',
 'Haselden',
 'Levingston',
 'Veltri',
 'Castillo',
 'Mencuccini',
 'Laub',
 'Marotta',
 'Howell',
 'Chan',
 'Verderose',
 'Powell',
 'Allgood',
 'Anthony',
 'Fazio',
 'Corriere',
 'Paniccia',
 'Denowitz',
 'Beresko',
 'Keep',
 'McGill',
 'Altopiedi',
 'Gellene',
 'Evangelista',
 'Hakeem',
 'Ramadan',
 'Buffington',
 'Malleris',
 'Mansfield',
 'Beasley',
 'London',
 'Rodriguez',
 'Freeze',
 'Chalumeau',
 'Curran',
 'Marcantonio',
 'George',
 'Fermaglich',
 'Wells',
 'Hershewe',
 'Gokal',
 'Franklin',
 'Haynes',
 'Talbert',
 'Briggs',
 'Wool',
 'Magenheim',
 'Adkinson',
 'Wong',
 'Arabo',
 'Duroseau',
 'Sanders',
 'Hardin',
 'Berger',
 'Breslin',
 'Orsborn',
 'Perry',
 'VanDeMark',
 'Curry',
 'Goldstein',
 'Levin',
 'Davis',
 'Shapiro',
 'Rombro',
 'Bell',
 'Kalish',
 'Kornblau',
 'Ray',
 'Sagot',
 'Jaffe',
 'Plimack',
 'MacDougall',
 'Potter',
 'Lewis',
 'Cramer',
 'White',
 'Chason',
 'Studenberg',
 'Downen',
 'Carpenter',
 'Engerman',
 'Jones',
 'Speare',
 'Kincannon',
 'Place',
 'Glazer',
 'Ertel',
 'Moss',
 'Schuldenfrei',
 'Kwawer',
 'Rosner',
 'Brown',
 'Fugate',
 'Wolf',
 'Stewart',
 'Mills',
 'Allweiss',
 'Ball',
 'Desmond',
 'Prunty',
 'Weed',
 'Seaman',
 'Gabe',
 'Tittle',
 'Davis',
 'Lindsay',
 'Martincavage',
 'Williams',
 'Fagerman',
 'Lane',
 'Walsh',
 'Hockman',
 'McKenzie',
 'Gilman',
 'Hymel',
 'Lampert',
 'Bridges',
 'Kinnier',
 'Lee',
 'Beauparlant',
 'Rowe',
 'Defillo-Millman',
 'Stempuzis',
 'Kale',
 'Hearns',
 'Nunez',
 'Maglio',
 'Prillaman',
 'Hale',
 'Haynes',
 'Smith',
 'Watson',
 'Mokhtari',
 'Owens',
 'Areces',
 'Knight',
 'Hersh',
 'Dorfman',
 'Levie',
 'Wells',
 'Ziontz',
 'Peters',
 'Boucher',
 'Nathanson',
 'Barlow',
 'Luckey',
 'Richard',
 'Dotson',
 'Sullivan',
 'Phillips',
 'Bomze',
 'Poole',
 'Pershan',
 'Nath',
 'Lucero',
 'Shah',
 'Mingo',
 'Houser',
 'Musselwhite',
 'Yenerall',
 'Davis',
 'Darby',
 'Paye',
 'Sanders',
 'Brinton',
 'Donnell',
 'Hinshaw',
 'Burke',
 'Como',
 'Furth',
 'Gehring',
 'Morris',
 'Wills',
 'Stern',
 'Stevens',
 'Reiter',
 'Chang',
 'Green',
 'Zafur',
 'Weisman',
 'Carvalho',
 'Bhargava',
 'Winer-Gebhart',
 'Kaimer',
 'Pallante',
 'Padron-Fragetta',
 'Santos',
 'Borza',
 'Buckman',
 'Ladan',
 'Navare',
 'Alo',
 'Blair',
 'Acheson',
 'Goldstein',
 'Vandeveld',
 'Quillen',
 'Crossan',
 'Thomas',
 'Yenari',
 'Gowan',
 'Mariani',
 'Cofield-Derrick',
 'Salladay',
 'Rudley',
 'Skelton',
 'Stoner',
 'Allred',
 'Keiser',
 'Bailey',
 'Vesely',
 'Hart',
 'Witherite',
 'Brewer',
 'Gervich',
 'Gillette',
 'Insler',
 'Mitchell',
 'Patras',
 'Sergent',
 'Vaudreuil',
 'Lorenz',
 'Wille',
 'Combs',
 'Johnston',
 'Keating',
 'Orsi',
 'Morse',
 'Tobias',
 'Boring',
 'Turos',
 'Wheatley',
 'Winsten',
 'Snell',
 'Griggs',
 'Boyer',
 'Taylor',
 'Urness',
 'Fritz',
 'Olivares',
 'Gutierrez',
 'Molleda',
 'Aparicio',
 'Schmidt',
 'McNamara',
 'Sardi',
 'Jacobs',
 'Sondergaard',
 'Misra',
 'Gordon',
 'Levinsky',
 'Cox',
 'Hatfield',
 'Washburn',
 'Svikis',
 'Dorval',
 'Summers',
 'Dandurand',
 'Regard',
 'Crenshaw',
 'Lagomarsino',
 'Michniak',
 'Young',
 'Amodeo-Vickery',
 'Anderson',
 'Caro',
 'McMillan',
 'Miller',
 'Watters',
 'Green',
 'Huston',
 'Baron',
 'Sugar',
 'Ciobanu',
 'Heckler',
 'Pawlak',
 'Shapiro',
 'Henson',
 'Bateman',
 'Carty',
 'Winder',
 'Alonso',
 'Almanzan',
 'Cos',
 'Aranda',
 'Dunlap',
 'Szakaly',
 'Agard',
 'Artus',
 'Ballerini',
 'Cohen',
 'Iacobelli',
 'Kimler',
 'Lemmon',
 'Prolman',
 'Smith',
 'Solomon',
 'Ausband',
 'Ezell',
 'Farley',
 'Miller',
 'Protzman',
 'Smith',
 'Sommerman',
 'Spiegel',
 'Bakos',
 'Bayer',
 'Beal',
 'Bersin',
 'Clifford',
 'Barr',
 'Burrell',
 'Clarke',
 'Eckert',
 'Johnson',
 'Schnack',
 'Skinner',
 'Chafin',
 'Lease',
 'Stebbins',
 'Grimes',
 'Glasgrow',
 'Huppert',
 'Jones',
 'Presberg',
 'Sabetta',
 'Stone',
 'Swain',
 'Tabenkin',
 'Greenwald',
 'Karim',
 'Feske',
 'Garruto',
 'Russo',
 'Stasio',
 'Fulkerson',
 'Ramon',
 'Schrader',
 'Storie',
 'Norton',
 'Agatston',
 'Haas',
 'Marty',
 'Quinn',
 'Wood',
 'Harakas',
 'Drucker',
 'Hoverman',
 'Hamelsky',
 'Renda',
 'Bainbridge',
 'Brown',
 'Cafiero',
 'Gibbs',
 'Gibbs',
 'Kinstler',
 'Kutsulis',
 'Mallon',
 'McCumber',
 'Morrissey',
 'Keefe',
 'Reinhardt',
 'Rodnite',
 'Rossetti',
 'Schatkin',
 'Smithart',
 'Thompson',
 'Jacobs',
 'Peters',
 'Calcagno',
 'Johnson',
 'Jacoby',
 'Kossover',
 'Drapkin',
 'Ellenberg',
 'Miller',
 'Shapiro',
 'Laplante',
 'Statmore',
 'Liefer',
 'Tillem',
 'Abraham',
 'Barker',
 'Carroll',
 'Casey',
 'Friedman',
 'Korduba',
 'Kulick',
 'Laskin',
 'Newcomb',
 'Rockman',
 'Romano',
 'Wubbenhorst',
 'Yoder',
 'Skier',
 'McGee',
 'Sacks',
 'Montroy',
 'Mooney',
 'Cassas',
 'Greher',
 'Nestor',
 'Carrington',
 'Ott',
 'Botti',
 'Cioffi',
 'Mazzeo',
 'Motel',
 'Walsh',
 'McGraw',
 'Hamil',
 'Kirschner',
 'Liverman',
 'Louis',
 'Macklin',
 'Pauley',
 'Schwing',
 'Steiker',
 'Wolf',
 'Dempster',
 'Rosner',
 'Mackenzie',
 'Rubin',
 'Magdy',
 'Blumer',
 'Nason',
 'Abramson',
 'Baker',
 'Caslowitz',
 'Goldwyn',
 'Murrie',
 'Muth',
 'Viola',
 'Wainwright',
 'Schwarz',
 'Epstein',
 'Henschel',
 'Shaul',
 'Sher',
 'Skemp',
 'Sky',
 'Slepian',
 'Garvis',
 'Adams',
 'Blum',
 'Houghton',
 'Neuwirth',
 'Richardson',
 'Sheeley',
 'Tarry',
 'Chasse',
 'Bokar',
 'Horn',
 'Jones',
 'Seibert',
 'Siegel',
 'Snyder',
 'Yung',
 'Willers',
 'Wise',
 'Wilson',
 'Wolfenson',
 'Wolff',
 'Kim',
 'Yiangou',
 'Zelman',
 'Johnson',
 'Hayes',
 'Hensler',
 'Long',
 'Rose',
 'Yun',
 'Stewart',
 'Figueredo',
 'Sanez',
 'Diaz',
 'Greene',
 'Kirk',
 'Wiggins',
 'Tekell',
 'Frazier',
 'Stevens',
 'Caine-Turner',
 'Snider',
 'Landes',
 'Dailey',
 'Elpers',
 'Keck',
 'Arellanes',
 'Burmeister',
 'Cancio',
 'Pollard',
 'Hartmann',
 'Vagotis',
 'Vecchio',
 'McDonald',
 'Caldwell',
 'Plakas',
 'Ziotas',
 'Morresi',
 'Testa',
 'Cicchiello',
 'Marino',
 'Simone',
 'Wright',
 'Taff',
 'Avetisyan',
 'Azadian',
 'Taneja',
 'Webster',
 'Johnson',
 'Steenson',
 'Guidoux',
 'Hotchkiss',
 'Adams',
 'Modak-Truran',
 'Meara',
 'Ganguly',
 'Sharma',
 'Perkins',
 'Price',
 'Buckley',
 'Leslie',
 'Foley',
 'Davis',
 'Washburn',
 'Brandau',
 'Staley',
 'Nowak',
 'Jones',
 'Lawler',
 'Steffens',
 'Worthington',
 'Cushing',
 'Stockmaster',
 'Tessneer',
 'Tobin-Levigne',
 'Trzynka',
 'Henderson',
 'Combs',
 'Barker',
 'Isobe',
 'Sheeley',
 'Siddall',
 'Curry',
 'Frank',
 'Trehub',
 'Hopcroft',
 'Carter',
 'Burr',
 'Ortiz',
 'Resnick',
 'Williams',
 'Guerra',
 'Petosky',
 'Scheurich',
 'Villarreal',
 'Moore',
 'Donovan',
 'Fowler',
 'Rice',
 'Skau',
 'Leahey',
 'Brown',
 'Seider',
 'Fraser',
 'Ford',
 'Daddario',
 'Kepner',
 'LaBella',
 'Guillory',
 'Manley',
 'Watkins',
 'Berger',
 'Heyns',
 'Morgan',
 ...]

In [46]:
name_list = [x.split(' ') for x in df['name']]
full_name_last_name_zip = list(zip(name_list, last_name_list))
full_name_last_name_zip

[(['A', 'Allsbrook', 'Richardson'], 'Richardson'),
 (['A', 'Elizabeth', 'Turner'], 'Turner'),
 (['A', 'J', 'Wambach'], 'Wambach'),
 (['A', 'Joseph', 'Guarino'], 'Guarino'),
 (['A', 'Omotayo', 'Orederu'], 'Orederu'),
 (['A', 'Randolph', 'Comba'], 'Comba'),
 (['A.', 'Blake', 'MacDonald'], 'MacDonald'),
 (['A.', 'Bowdre', 'Banks', 'Jr.'], 'Banks'),
 (['A.', 'Bryan', 'Tomlinson'], 'Tomlinson'),
 (['A.', 'Collin', 'Cherry,', 'Esquire'], 'Cherry'),
 (['A.', 'Craig', 'Purcell'], 'Purcell'),
 (['A.', 'David', 'Fawal'], 'Fawal'),
 (['A.', 'Dawn', 'Hayes'], 'Hayes'),
 (['A.', 'Dwight', 'Hood'], 'Hood'),
 (['A.', 'Gregory', 'Ramos'], 'Ramos'),
 (['A.', 'Gus', 'Mastracci'], 'Mastracci'),
 (['A.', 'Harold', 'Datz'], 'Datz'),
 (['A.', 'Howard', 'Williams'], 'Williams'),
 (['A.', 'I.', 'Stacey', 'Williams'], 'Williams'),
 (['A.', 'J.', 'Balbo,', 'Esq.'], 'Balbo'),
 (['A.', 'Jack', 'Hinton'], 'Hinton'),
 (['A.', 'James', 'Leeds'], 'Leeds'),
 (['A.', 'Jeff', 'Kemp'], 'Kemp'),
 (['A.', 'Lance', 'Tonn'], 'Tonn'),
 (['A.', 'Lou', 'Benassi'], 'Benassi'),
 (['A.', 'Mac', 'Martinson'], 'Martinson'),
 (['A.', 'Major', 'Bey'], 'Bey'),
 (['A.', 'Mark', 'O', 'Danovich'], 'Danovich'),
 (['A.', 'Michael', 'Nalu'], 'Nalu'),
 (['A.', 'Newton', 'Dilley'], 'Dilley'),
 (['A.', 'O.', 'Khalil,', 'Esq.'], 'Khalil'),
 (['A.', 'P.', 'Gibbs,', 'Esq.'], 'Gibbs'),
 (['A.', 'Paul', 'Spinella'], 'Spinella'),
 (['A.', 'Paul', 'Weissenstein', 'Jr.'], 'Weissenstein'),
 (['A.', 'Philip', 'Lomonaco'], 'Lomonaco'),
 (['A.', 'Powell', 'Sanders'], 'Sanders'),
 (['A.', 'Randall', 'Friday'], 'Friday'),
 (['A.', 'Richard', 'Snell'], 'Snell'),
 (['A.', 'Robert', 'E.', 'Thomson'], 'Thomson'),
 (['A.', 'Robert', 'Gloeser'], 'Gloeser'),
 (['A.', 'Ronald', 'Sirna', 'Jr.'], 'Sirna'),
 (['A.', 'Roy', 'DeCaro'], 'DeCaro'),
 (['A.', 'Russell', 'Janklow'], 'Janklow'),
 (['A.', 'Scot', 'Chase'], 'Chase'),
 (['A.', 'Scott', 'Tillery'], 'Tillery'),
 (['A.', 'Shane', 'Mattingly'], 'Mattingly'),
 (['A.', 'Spencer', 'McManes', 'Jr.'], 'McManes'),
 (['A.', 'Troy', 'Hunter'], 'Hunter'),
 (['A.', 'W.', 'Tony', 'Tauke'], 'Tauke'),
 (['A.', 'Wade', 'James'], 'James'),
 (['A.', 'William', 'Lucas'], 'Lucas'),
 (['A.r.', 'Mander', 'III.'], 'Mander'),
 (['Aaron', 'A.', 'De', 'Angelis'], 'Angelis'),
 (['Aaron', 'Abraham', 'Krolik,', 'Esquire'], 'Krolik'),
 (['Aaron', 'C', 'Amore'], 'Amore'),
 (['Aaron', 'C', 'Gregg'], 'Gregg'),
 (['Aaron', 'C.', 'Denton'], 'Denton'),
 (['Aaron', 'C.', 'Johnson'], 'Johnson'),
 (['Aaron', 'Charles', 'Ryan'], 'Ryan'),
 (['Aaron', 'D', 'Felton'], 'Felton'),
 (['Aaron', 'D', 'Randall'], 'Randall'),
 (['Aaron', 'D.', 'Bundy'], 'Bundy'),
 (['Aaron', 'D.', 'Crane'], 'Crane'),
 (['Aaron', 'D.', 'Delgado'], 'Delgado'),
 (['Aaron', 'D.', 'Eiesland'], 'Eiesland'),
 (['Aaron', 'D.', 'Lauter'], 'Lauter'),
 (['Aaron', 'D.', 'Salberg'], 'Salberg'),
 (['Aaron', 'D.', 'Speck'], 'Speck'),
 (['Aaron', 'David', 'Wiseley'], 'Wiseley'),
 (['Aaron', 'F.', 'Glazer'], 'Glazer'),
 (['Aaron', 'Felton', 'Allison'], 'Allison'),
 (['Aaron', 'Garrett'], 'Garrett'),
 (['Aaron', 'H.', 'R.', 'Ginkens'], 'Ginkens'),
 (['Aaron', 'J.', 'Allen'], 'Allen'),
 (['Aaron', 'J.', 'Broussard'], 'Broussard'),
 (['Aaron', 'J.', 'Rolen'], 'Rolen'),
 (['Aaron', 'Jainchill'], 'Jainchill'),
 (['Aaron', 'M.', 'House'], 'House'),
 (['Aaron', 'M.', 'Kelly'], 'Kelly'),
 (['Aaron', 'M.', 'Reed'], 'Reed'),
 (['Aaron', 'N.', 'Woods'], 'Woods'),
 (['Aaron', 'R.', 'Maurice'], 'Maurice'),
 (['Aaron', 'R.', 'Sobel'], 'Sobel'),
 (['Aaron', 'Ritchie'], 'Ritchie'),
 (['Aaron', 'Rodgers'], 'Rodgers'),
 (['Aaron', 'Shawn', 'Hicks,', 'Esq.'], 'Hicks'),
 (['Aaron', 'W.', 'Ferguson'], 'Ferguson'),
 (['Aaron', 'W.', 'Graves'], 'Graves'),
 (['Aaron', 'W.', 'Rapier'], 'Rapier'),
 (['Aaron', 'W.', 'Rodenburg'], 'Rodenburg'),
 (['Aaron', 'W.', 'Smith'], 'Smith'),
 (['Aaron', 'Watson'], 'Watson'),
 (['Aaron', 'Wm.', 'Sachs'], 'Sachs'),
 (['Abbe', 'Jolles'], 'Jolles'),
 (['Abbott', 'S.', 'Fenichel'], 'Fenichel'),
 (['Abby', 'Marie', 'Spears'], 'Spears'),
 (['Abby', 'Morrow', 'Richardson'], 'Richardson'),
 (['Abdalla', 'J', 'Innabi'], 'Innabi'),
 (['Abdulhakim', 'Saadiq'], 'Saadiq'),
 (['Abe', 'Omerhodic'], 'Omerhodic'),
 (['Abe', 'R.', 'Paul'], 'Paul'),
 (['Abel', 'A.', 'Orendain'], 'Orendain'),
 (['Abelino', 'Reyna'], 'Reyna'),
 (['Abraham', 'B', 'Cardenas,', 'Esquire'], 'Cardenas'),
 (['Abraham', 'J.', 'Mayers'], 'Mayers'),
 (['Abraham', 'J.', 'Saad'], 'Saad'),
 (['Abraham', 'Jacob', 'Nievod'], 'Nievod'),
 (['Abraham', 'P', 'Kassis'], 'Kassis'),
 (['Abraham', 'Reingold'], 'Reingold'),
 (['Ada', 'Maria', 'Barreto'], 'Barreto'),
 (['Adam', 'A.', 'Studnicki'], 'Studnicki'),
 (['Adam', 'B.', 'Brown'], 'Brown'),
 (['Adam', 'B.', 'Kuenning'], 'Kuenning'),
 (['Adam', 'B.', 'Lederman,', 'Esq.'], 'Lederman'),
 (['Adam', 'B.', 'Riback'], 'Riback'),
 (['Adam', 'B.', 'Schwartz'], 'Schwartz'),
 (['Adam', 'Barnett'], 'Barnett'),
 (['Adam', 'C.', 'Loeb'], 'Loeb'),
 (['Adam', 'Carlson'], 'Carlson'),
 (['Adam', 'Chrzan'], 'Chrzan'),
 (['Adam', 'Collins'], 'Collins'),
 (['Adam', 'D.', 'Blechman'], 'Blechman'),
 (['Adam', 'D.', 'Herzog'], 'Herzog'),
 (['Adam', 'D.', 'Young'], 'Young'),
 (['Adam', 'Davis'], 'Davis'),
 (['Adam', 'Demetri'], 'Demetri'),
 (['Adam', 'E', 'Bossov'], 'Bossov'),
 (['Adam', 'E.', 'Carr'], 'Carr'),
 (['Adam', 'E.', 'Schramm'], 'Schramm'),
 (['Adam', 'Evans'], 'Evans'),
 (['Adam', 'Flores'], 'Flores'),
 (['Adam', 'G.', 'Cross'], 'Cross'),
 (['Adam', 'Getson,', 'Esq.'], 'Getson'),
 (['Adam', 'Hill'], 'Hill'),
 (['Adam', 'J', 'Malinowski'], 'Malinowski'),
 (['Adam', 'J.', 'Bean,', 'Esq.'], 'Bean'),
 (['Adam', 'J.', 'Blank'], 'Blank'),
 (['Adam', 'J.', 'Curry'], 'Curry'),
 (['Adam', 'J.', 'Resmini,', 'Esq.'], 'Resmini'),
 (['Adam', 'J.', 'Soibelman'], 'Soibelman'),
 (['Adam', 'J.', 'Tabak'], 'Tabak'),
 (['Adam', 'J.', 'Teller'], 'Teller'),
 (['Adam', 'J.', 'Wax'], 'Wax'),
 (['Adam', 'Joseph', 'Russo'], 'Russo'),
 (['Adam', 'K.', 'Vernau'], 'Vernau'),
 (['Adam', 'L.', 'Rodd'], 'Rodd'),
 (['Adam', 'M.', 'Brown'], 'Brown'),
 (['Adam', 'M.', 'Jurach'], 'Jurach'),
 (['Adam', 'M.', 'Stefancic'], 'Stefancic'),
 (['Adam', 'Malone'], 'Malone'),
 (['Adam', 'Mazonson'], 'Mazonson'),
 (['Adam', 'Meltsner'], 'Meltsner'),
 (['Adam', 'P.', 'Cerbone'], 'Cerbone'),
 (['Adam', 'P.', 'Kossayda'], 'Kossayda'),
 (['Adam', 'Prochaska'], 'Prochaska'),
 (['Adam', 'Pugh'], 'Pugh'),
 (['Adam', 'R', 'Glinn'], 'Glinn'),
 (['Adam', 'S.', 'Baker'], 'Baker'),
 (['Adam', 'S.', 'Bernstein'], 'Bernstein'),
 (['Adam', 'S.', 'Hall'], 'Hall'),
 (['Adam', 'Scott', 'Weintraub'], 'Weintraub'),
 (['Adam', 'Symington'], 'Symington'),
 (['Adam', 'T.', 'Johnson'], 'Johnson'),
 (['Adam', 'T.', 'Williamson'], 'Williamson'),
 (['Adam', 'Trop'], 'Trop'),
 (['Addison', 'Kennon', 'Goff', 'III'], 'Goff'),
 (['Adele', 'M.', 'Blackmore'], 'Blackmore'),
 (['Adele', 'R.', 'Jacobs'], 'Jacobs'),
 (['Adnan', 'Horan'], 'Horan'),
 (['Adolfo', 'Lara'], 'Lara'),
 (['AdoLisa', 'Anarado'], 'Anarado'),
 (['Adolph', 'J.', 'Levy'], 'Levy'),
 (['Adolph', 'P.', 'Sicheri'], 'Sicheri'),
 (['Adrian', 'A.', 'Ellis'], 'Ellis'),
 (['Adrian', 'B.', 'Dunning'], 'Dunning'),
 (['Adrian', 'C.', 'Hunte'], 'Hunte'),
 (['Adrian', 'H.', 'Altshuler'], 'Altshuler'),
 (['Adrian', 'Hoosier'], 'Hoosier'),
 (['Adrian', 'J', 'Wasko'], 'Wasko'),
 (['Adrian', 'L.', 'Meyer'], 'Meyer'),
 (['Adrian', 'R.', 'Peguese'], 'Peguese'),
 (['Adrian', 'Vernon', 'Hershey'], 'Hershey'),
 (['Adriel', 'B.', 'Villarreal'], 'Villarreal'),
 (['Adrien', 'C.', 'Pickard'], 'Pickard'),
 (['Adrienne', 'C.', 'Snelling'], 'Snelling'),
 (['Adrienne', 'D.', 'Logeman'], 'Logeman'),
 (['Adrienne', 'J.', 'Burke'], 'Burke'),
 (['Adrienne', 'R', 'Baranoff,', 'Esq.'], 'Baranoff'),
 (['Adrienne', 'R', 'Klein'], 'Klein'),
 (['Adrienne', 'Rachel', 'Hahn'], 'Hahn'),
 (['Adrienne', 'S.', 'Davis'], 'Davis'),
 (['Adrienne', 'S.', 'King'], 'King'),
 (['Agatha', 'K.', 'Raynor'], 'Raynor'),
 (['Agnes', 'M.', 'Petersen'], 'Petersen'),
 (['Agostinho', 'J.', 'Ribeiro'], 'Ribeiro'),
 (['Agostino', 'Cammisa'], 'Cammisa'),
 (['Aidan', 'Cyril', 'Reynolds'], 'Reynolds'),
 (['Aihui', 'Su'], 'Su'),
 (['Aiken', 'Fletcher', 'Dyches'], 'Dyches'),
 (['Aileen', 'Droughton'], 'Droughton'),
 (['Aileen', 'M.', 'Leipprandt'], 'Leipprandt'),
 (['Aimee', 'E.', 'Rabalais'], 'Rabalais'),
 (['Aisling', 'A.', 'Murphy'], 'Murphy'),
 (['Aksana', 'Moshaiv'], 'Moshaiv'),
 (['Al', 'F.', 'Amer'], 'Amer'),
 (['Al', 'Iacocca,', 'Esquire'], 'Iacocca'),
 (['Al', 'Joseph', 'Carrion'], 'Carrion'),
 (['Al', 'Schallau'], 'Schallau'),
 (['Al.', 'Hom'], 'Hom'),
 (['Alali', 'M', 'Tamuno'], 'Tamuno'),
 (['Alan', 'A', 'Carrico'], 'Carrico'),
 (['Alan', 'Aleksander'], 'Aleksander'),
 (['Alan', 'Alhadeff'], 'Alhadeff'),
 (['Alan', 'B', 'Weber'], 'Weber'),
 (['Alan', 'B.', 'Fish'], 'Fish'),
 (['Alan', 'B.', 'Havis'], 'Havis'),
 (['Alan', 'B.', 'Neurick'], 'Neurick'),
 (['Alan', 'B.', 'Waln'], 'Waln'),
 (['Alan', 'Banov'], 'Banov'),
 (['Alan', 'Bellenger'], 'Bellenger'),
 (['Alan', 'Benjamin', 'Miller'], 'Miller'),
 (['Alan', 'Brent', 'Geohagan'], 'Geohagan'),
 (['Alan', 'C.', 'Anchell'], 'Anchell'),
 (['Alan', 'C.', 'Betz'], 'Betz'),
 (['Alan', 'C.', 'Espy'], 'Espy'),
 (['Alan', 'D', 'Taylor'], 'Taylor'),
 (['Alan', 'D.', 'Bell'], 'Bell'),
 (['Alan', 'D.', 'Budman'], 'Budman'),
 (['Alan', 'D.', 'Henderson'], 'Henderson'),
 (['Alan', 'D.', 'Levine'], 'Levine'),
 (['Alan', 'D.', 'Watson'], 'Watson'),
 (['Alan', 'E.', 'Toll'], 'Toll'),
 (['Alan', 'F', 'Varner'], 'Varner'),
 (['Alan', 'F.', 'Smietanski'], 'Smietanski'),
 (['Alan', 'Floria'], 'Floria'),
 (['Alan', 'G.', 'Blatnikoff'], 'Blatnikoff'),
 (['Alan', 'G.', 'Greenberg'], 'Greenberg'),
 (['Alan', 'Ginsberg'], 'Ginsberg'),
 (['Alan', 'Graham', 'Greer'], 'Greer'),
 (['Alan', 'H', 'Greenberg'], 'Greenberg'),
 (['Alan', 'H.', 'Barbanel'], 'Barbanel'),
 (['Alan', 'Hunt'], 'Hunt'),
 (['Alan', 'I.', 'Schimmel'], 'Schimmel'),
 (['Alan', 'J', 'Markman'], 'Markman'),
 (['Alan', 'J', 'Ominsky'], 'Ominsky'),
 (['Alan', 'J.', 'Baldwin'], 'Baldwin'),
 (['Alan', 'J.', 'Belsky'], 'Belsky'),
 (['Alan', 'J.', 'Booth,', 'Esq.'], 'Booth'),
 (['Alan', 'J.', 'Cohen'], 'Cohen'),
 (['Alan', 'J.', 'Golden'], 'Golden'),
 (['Alan', 'J.', 'Konigsberg'], 'Konigsberg'),
 (['Alan', 'J.', 'Nuta'], 'Nuta'),
 (['Alan', 'J.', 'Statman'], 'Statman'),
 (['Alan', 'Jay', 'Braverman'], 'Braverman'),
 (['Alan', 'Jay', 'Foxman'], 'Foxman'),
 (['Alan', 'Jay', 'Lander'], 'Lander'),
 (['Alan', 'Jay', 'Lerner'], 'Lerner'),
 (['Alan', 'Jermaine', 'Stratton'], 'Stratton'),
 (['Alan', 'K.', 'Foe'], 'Foe'),
 (['Alan', 'Kansas'], 'Kansas'),
 (['Alan', 'Kolod'], 'Kolod'),
 (['Alan', 'Kreshtool'], 'Kreshtool'),
 (['Alan', 'L', 'Mealy'], 'Mealy'),
 (['Alan', 'L.', 'Joseph'], 'Joseph'),
 (['Alan', 'L.', 'Newman'], 'Newman'),
 (['Alan', 'L.', 'Schwalbe'], 'Schwalbe'),
 (['Alan', 'L.', 'Sirkin'], 'Sirkin'),
 (['Alan', 'L.', 'Whitted'], 'Whitted'),
 (['Alan', 'M', 'Kraut'], 'Kraut'),
 (['Alan', 'M', 'Tanenbaum'], 'Tanenbaum'),
 (['Alan', 'M', 'Tepper'], 'Tepper'),
 (['Alan', 'M.', 'Greenberg'], 'Greenberg'),
 (['Alan', 'M.', 'Purdie'], 'Purdie'),
 (['Alan', 'M.', 'Salkow'], 'Salkow'),
 (['Alan', 'M.', 'Wolinsky'], 'Wolinsky'),
 (['Alan', 'Michael', 'Foody'], 'Foody'),
 (['Alan', 'Molina'], 'Molina'),
 (['Alan', 'Molina'], 'Molina'),
 (['Alan', 'P.', 'Bayham', 'Jr.'], 'Bayham'),
 (['Alan', 'P.', 'Dove'], 'Dove'),
 (['Alan', 'Patrick', 'Taylor'], 'Taylor'),
 (['Alan', 'Pearlman'], 'Pearlman'),
 (['Alan', 'R', 'Davis'], 'Davis'),
 (['Alan', 'R.', 'Beard'], 'Beard'),
 (['Alan', 'R.', 'Cochran'], 'Cochran'),
 (['Alan', 'R.', 'Goodman'], 'Goodman'),
 (['Alan', 'R.', 'Lebowitz'], 'Lebowitz'),
 (['Alan', 'R.', 'LeCours'], 'LeCours'),
 (['Alan', 'R.', 'Levy'], 'Levy'),
 (['Alan', 'R.', 'Pfaff'], 'Pfaff'),
 (['Alan', 'Robert', 'Kolodny'], 'Kolodny'),
 (['Alan', 'Roberts'], 'Roberts'),
 (['Alan', 'Rosenberg'], 'Rosenberg'),
 (['Alan', 'S.', 'Baum'], 'Baum'),
 (['Alan', 'S.', 'Dambrov'], 'Dambrov'),
 (['Alan', 'S.', 'Friedman'], 'Friedman'),
 (['Alan', 'S.', 'Funk'], 'Funk'),
 (['Alan', 'S.', 'Gold'], 'Gold'),
 (['Alan', 'S.', 'Levine,', 'Esq.'], 'Levine'),
 (['Alan', 'S.', 'Pierce'], 'Pierce'),
 (['Alan', 'Scott', 'Miller'], 'Miller'),
 (['Alan', 'Scott', 'Pickel'], 'Pickel'),
 (['Alan', 'Silko'], 'Silko'),
 (['Alan', 'Starker'], 'Starker'),
 (['Alan', 'Stegall'], 'Stegall'),
 (['Alan', 'Steven', 'Rubin'], 'Rubin'),
 (['Alan', 'Sylvester'], 'Sylvester'),
 (['Alan', 'V.', 'Johnson'], 'Johnson'),
 (['Alan', 'W.', 'Cohn'], 'Cohn'),
 (['Alan', 'Wagner'], 'Wagner'),
 (['Alan', 'Y.', 'Medvin'], 'Medvin'),
 (['Alana', 'Blatt', 'Clements'], 'Clements'),
 (['Alaric', 'A.', 'Henry'], 'Henry'),
 (['Alban', 'Dunisha'], 'Dunisha'),
 (['Albert', 'A.', 'Biel', 'Jr.'], 'Biel'),
 (['Albert', 'A.', 'Wolf'], 'Wolf'),
 (['Albert', 'Aaron'], 'Aaron'),
 (['Albert', 'Andre', 'Mitchell'], 'Mitchell'),
 (['Albert', 'Dragon'], 'Dragon'),
 (['Albert', 'E.', 'Davies'], 'Davies'),
 (['Albert', 'E.', 'Desrosiers'], 'Desrosiers'),
 (['Albert', 'E.', 'Fershing'], 'Fershing'),
 (['Albert', 'E.', 'Hollan'], 'Hollan'),
 (['Albert', 'E.', 'Jones'], 'Jones'),
 (['Albert', 'E.', 'Moon'], 'Moon'),
 (['Albert', 'E.', 'Ranum'], 'Ranum'),
 (['Albert', 'F.', 'Maier', 'Jr.'], 'Maier'),
 (['Albert', 'F.', 'Ries'], 'Ries'),
 (['Albert', 'F.', 'Shamash'], 'Shamash'),
 (['Albert', 'Farrah'], 'Farrah'),
 (['Albert', 'G.', 'Hubby', 'III'], 'Hubby'),
 (['Albert', 'Guadagno'], 'Guadagno'),
 (['Albert', 'J', 'Rescinio'], 'Rescinio'),
 (['Albert', 'J', 'Sreter'], 'Sreter'),
 (['Albert', 'J.', 'Bannon'], 'Bannon'),
 (['Albert', 'J.', 'DeCusati'], 'DeCusati'),
 (['Albert', 'J.', 'Fiorella'], 'Fiorella'),
 (['Albert', 'J.', 'Slap'], 'Slap'),
 (['Albert', 'Joseph', 'Bolet', 'III'], 'Bolet'),
 (['Albert', 'L.', 'Saslow'], 'Saslow'),
 (['Albert', 'L.', 'Wheeler', 'III'], 'Wheeler'),
 (['Albert', 'M.', 'Messer'], 'Messer'),
 (['Albert', 'M.', 'Pearson', 'III'], 'Pearson'),
 (['Albert', 'N.', 'Thiel', 'Jr.'], 'Thiel'),
 (['Albert', 'R.', 'Matthews'], 'Matthews'),
 (['Albert', 'S', 'Lazarus'], 'Lazarus'),
 (['Albert', 'Salvi'], 'Salvi'),
 (['Albert', 'T.', 'Van', 'Huff'], 'Huff'),
 (['Albert', 'W.', 'Chianese,', 'Esq.'], 'Chianese'),
 (['Albert', 'W.', 'Cornachio', 'III,', 'Esq.'], 'Cornachio'),
 (['Albert', 'Wesley', 'Miller', 'III'], 'Miller'),
 (['Alberto', 'Berrones'], 'Berrones'),
 (['Alberto', 'Franco'], 'Franco'),
 (['Alberto', 'Guadagno'], 'Guadagno'),
 (['Alberto', 'Virgen'], 'Virgen'),
 (['Alden', 'C.', 'Harrington'], 'Harrington'),
 (['Aldo', 'Beltrano'], 'Beltrano'),
 (['Aldo', 'J.', 'Stolte'], 'Stolte'),
 (['Alec', 'Hanus'], 'Hanus'),
 (['Alec', 'Wisner'], 'Wisner'),
 (['Alecia', 'Elston'], 'Elston'),
 (['Alejandro', 'David', 'Szwarcsztejn'], 'Szwarcsztejn'),
 (['Alejandro', 'Fiol'], 'Fiol'),
 (['Alejandro', 'J.', 'Rodriguez'], 'Rodriguez'),
 (['Alesia', 'H.', 'Days,', 'Esq.'], 'Days'),
 (['Alesia', 'R.', 'Strand'], 'Strand'),
 (['Alessandro', 'F.', 'Marra,', 'Esq.'], 'Marra'),
 (['Alessandro', 'Giribaldi'], 'Giribaldi'),
 (['Alex', 'A.', 'Lauricella'], 'Lauricella'),
 (['Alex', 'A.', 'Omrani,', 'Esq.'], 'Omrani'),
 (['Alex', 'B', 'Scheingross'], 'Scheingross'),
 (['Alex', 'Brian', 'Wallach'], 'Wallach'),
 (['Alex', 'C.', 'Dunn'], 'Dunn'),
 (['Alex', 'C.', 'Elder'], 'Elder'),
 (['Alex', 'D.', 'Chapman', 'Jr.'], 'Chapman'),
 (['Alex', 'D.', 'Cheng'], 'Cheng'),
 (['Alex', 'F', 'Philippone'], 'Philippone'),
 (['Alex', 'Ghibaudo'], 'Ghibaudo'),
 (['Alex', 'Goldberg'], 'Goldberg'),
 (['Alex', 'H.', 'Sitz', 'III'], 'Sitz'),
 (['Alex', 'Hanna,', 'Esq.'], 'Hanna'),
 (['Alex', 'J.', 'Miller'], 'Miller'),
 (['Alex', 'J.', 'Remick'], 'Remick'),
 (['Alex', 'N.', 'Kapetan'], 'Kapetan'),
 (['Alex', 'Rabin'], 'Rabin'),
 (['Alex', 'S.', 'Friedland'], 'Friedland'),
 (['Alex', 'Thomas', 'Postic'], 'Postic'),
 (['Alex', 'W.', 'Nocerino'], 'Nocerino'),
 (['Alex', 'W.', 'Russell,', 'J.D.,', 'C.P.A.'], 'Russell'),
 (['Alex', 'Wyatt', 'Wright'], 'Wright'),
 (['Alexa', 'D', 'Amato', 'Barrera'], 'Barrera'),
 (['Alexander', 'Begum'], 'Begum'),
 (['Alexander', 'D.', 'Boyd'], 'Boyd'),
 (['Alexander', 'D.', 'Crecca'], 'Crecca'),
 (['Alexander', 'E.', 'Sklavos'], 'Sklavos'),
 (['Alexander', 'F.', 'Reichert'], 'Reichert'),
 (['Alexander', 'Gray', 'Hait'], 'Hait'),
 (['Alexander', 'Gregory', 'Rozman'], 'Rozman'),
 (['Alexander', 'J.', 'Gordon'], 'Gordon'),
 (['Alexander', 'J.', 'Jamiolkowski'], 'Jamiolkowski'),
 (['Alexander', 'J.', 'Kemeny'], 'Kemeny'),
 (['Alexander', 'J.', 'Smith'], 'Smith'),
 (['Alexander', 'James', 'Ginsburg'], 'Ginsburg'),
 (['Alexander', 'Joseph', 'Alfano'], 'Alfano'),
 (['Alexander', 'K.', 'Davison'], 'Davison'),
 (['Alexander', 'Karasik'], 'Karasik'),
 (['Alexander', 'Latanision'], 'Latanision'),
 (['Alexander', 'Levine,', 'Esq.'], 'Levine'),
 (['Alexander', 'Louis', 'Silow'], 'Silow'),
 (['Alexander', 'Lumelsky'], 'Lumelsky'),
 (['Alexander', 'M.', 'Dashe'], 'Dashe'),
 (['Alexander', 'Mark', 'Weinberg'], 'Weinberg'),
 (['Alexander', 'N', 'Levay', 'Jr.'], 'Levay'),
 (['Alexander', 'R', 'Cain'], 'Cain'),
 (['Alexander', 'S.', 'Kammer'], 'Kammer'),
 (['Alexander', 'Simanovsky'], 'Simanovsky'),
 (['Alexandra', 'Erna', 'Mora'], 'Mora'),
 (['Alexandra', 'Hull'], 'Hull'),
 (['Alexandra', 'J.', 'Schultz'], 'Schultz'),
 (['Alexandre', 'E.', 'Bonin'], 'Bonin'),
 (['Alexia', 'Pittas-Giroux'], 'Pittas-Giroux'),
 (['Alexis', 'A.', 'Langella'], 'Langella'),
 (['Alexis', 'S.', 'Mullaney'], 'Mullaney'),
 (['Alf', 'E.', 'Sivertson'], 'Sivertson'),
 (['Alf', 'R.', 'H.', 'R.', 'Langan'], 'Langan'),
 (['Alford', 'Haselden'], 'Haselden'),
 (['Alfred', 'A', 'Levingston'], 'Levingston'),
 (['Alfred', 'A', 'Veltri'], 'Veltri'),
 (['Alfred', 'B.', 'Castillo', 'Jr.'], 'Castillo'),
 (['Alfred', 'B.', 'Mencuccini'], 'Mencuccini'),
 (['Alfred', 'C.', 'Laub'], 'Laub'),
 (['Alfred', 'E.', 'Marotta'], 'Marotta'),
 (['Alfred', 'G.', 'Howell'], 'Howell'),
 (['Alfred', 'H.', 'Chan'], 'Chan'),
 (['Alfred', 'J', 'Verderose'], 'Verderose'),
 (['Alfred', 'Jackson', 'Powell', 'Jr.'], 'Powell'),
 (['Alfred', 'L.', 'Allgood'], 'Allgood'),
 (['Alfred', 'M.', 'Anthony'], 'Anthony'),
 (['Alfred', 'M.', 'Fazio'], 'Fazio'),
 (['Alfred', 'N.', 'Corriere'], 'Corriere'),
 (['Alfred', 'Paniccia', 'Jr.'], 'Paniccia'),
 (['Alfred', 'Paul', 'Denowitz'], 'Denowitz'),
 (['Alfred', 'R.', 'Beresko'], 'Beresko'),
 (['Alfred', 'R.', 'Keep'], 'Keep'),
 (['Alfred', 'T', 'McGill'], 'McGill'),
 (['Alfred', 'V.', 'Altopiedi'], 'Altopiedi'),
 (['Alfred', 'V.', 'Gellene,', 'Esq.'], 'Gellene'),
 (['Alfredo', 'G.', 'Evangelista'], 'Evangelista'),
 (['Ali', 'Hakeem'], 'Hakeem'),
 (['Ali', 'Stephen', 'Ramadan'], 'Ramadan'),
 (['Alice', 'A.', 'Buffington'], 'Buffington'),
 (['Alice', 'A.', 'Malleris'], 'Malleris'),
 (['Alice', 'K', 'Mansfield'], 'Mansfield'),
 (['Alice', 'M', 'Beasley'], 'Beasley'),
 (['Alice', 'Oppenheim', 'London'], 'London'),
 (['Alice', 'Rodriguez'], 'Rodriguez'),
 (['Alicia', 'C.', 'Freeze,', 'Esq.'], 'Freeze'),
 (['Alicia', 'P.', 'Chalumeau,', 'Esq.'], 'Chalumeau'),
 (['Alicia', 'Sarah', 'Curran'], 'Curran'),
 (['Aline', 'O.', 'Marcantonio'], 'Marcantonio'),
 (['Alisa', 'E.', 'George'], 'George'),
 (['Alisa', 'L.', 'Silverstein', 'Fermaglich'], 'Fermaglich'),
 (['Alison', 'Courtney', 'Wells'], 'Wells'),
 (['Alison', 'Hershewe'], 'Hershewe'),
 (['Alison', 'S.', 'Gokal'], 'Gokal'),
 (['Alison', 'Shontz', 'Franklin'], 'Franklin'),
 (['Alison', 'White', 'Haynes'], 'Haynes'),
 (['Alison', 'Whitney', 'Talbert'], 'Talbert'),
 (['Alison', 'Wholey', 'Briggs,', 'RN,', 'Esq.'], 'Briggs'),
 (['Alissa', 'Joy', 'Wool,', 'Esq.'], 'Wool'),
 (['Alissa', 'Sammarco', 'Magenheim'], 'Magenheim'),
 (['Alistair', 'Andrew', 'Adkinson'], 'Adkinson'),
 (['Alister', 'Wong'], 'Wong'),
 (['Alivia', 'Kassab', 'Arabo'], 'Arabo'),
 (['Alix', 'Duroseau', 'Jr.'], 'Duroseau'),
 (['Alix', 'H', 'Sanders'], 'Sanders'),
 (['Allain', 'F.', 'Hardin'], 'Hardin'),
 (['Allan', 'Berger'], 'Berger'),
 (['Allan', 'C.', 'Breslin'], 'Breslin'),
 (['Allan', 'C.', 'Orsborn'], 'Orsborn'),
 (['Allan', 'C.', 'Perry'], 'Perry'),
 (['Allan', 'Charles', 'VanDeMark'], 'VanDeMark'),

In [47]:
first_name_list = []
title_list = ['mrs', 'hon']
for x in full_name_last_name_zip:
    first_name_found = False
    sub_name_index = 0
    #Find the number of sub-names in the name
    subnames_len = len(x[0])
    #Remove punctuation:
    while sub_name_index < subnames_len:
        #Get the current clean name
        clean_name = x[0][sub_name_index].translate(str.maketrans('', '', string.punctuation))
        if clean_name == x[1]:
            break
        #If the name is less than 2 characters, move to the next name
        if len(clean_name) <= 2 or clean_name.lower() in title_list:
            sub_name_index += 1
        else:
            first_name_found = True
            break
    if first_name_found:
        first_name_list.append(clean_name)
    else:
        first_name_list.append('')
first_name_list

['Allsbrook',
 'Elizabeth',
 '',
 'Joseph',
 'Omotayo',
 'Randolph',
 'Blake',
 'Bowdre',
 'Bryan',
 'Collin',
 'Craig',
 'David',
 'Dawn',
 'Dwight',
 'Gregory',
 'Gus',
 'Harold',
 'Howard',
 'Stacey',
 '',
 'Jack',
 'James',
 'Jeff',
 'Lance',
 'Lou',
 'Mac',
 'Major',
 'Mark',
 'Michael',
 'Newton',
 '',
 '',
 'Paul',
 'Paul',
 'Philip',
 'Powell',
 'Randall',
 'Richard',
 'Robert',
 'Robert',
 'Ronald',
 'Roy',
 'Russell',
 'Scot',
 'Scott',
 'Shane',
 'Spencer',
 'Troy',
 'Tony',
 'Wade',
 'William',
 '',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Aaron',
 'Abbe',
 'Abbott',
 'Abby',
 'Abby',
 'Abdalla',
 'Abdulhakim',
 'Abe',
 'Abe',
 'Abel',
 'Abelino',
 'Abraham',
 'Abraham',
 'Abraham',
 'Abraham',
 'Abraham',
 'Abraham',
 'Ada',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Adam',
 'Addison',
 'Adele',
 'Adele',
 'Adnan',
 'Adolfo',
 'AdoLisa',
 'Adolph',
 'Adolph',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adrian',
 'Adriel',
 'Adrien',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Adrienne',
 'Agatha',
 'Agnes',
 'Agostinho',
 'Agostino',
 'Aidan',
 'Aihui',
 'Aiken',
 'Aileen',
 'Aileen',
 'Aimee',
 'Aisling',
 'Aksana',
 '',
 '',
 'Joseph',
 '',
 '',
 'Alali',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alan',
 'Alana',
 'Alaric',
 'Alban',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Albert',
 'Alberto',
 'Alberto',
 'Alberto',
 'Alberto',
 'Alden',
 'Aldo',
 'Aldo',
 'Alec',
 'Alec',
 'Alecia',
 'Alejandro',
 'Alejandro',
 'Alejandro',
 'Alesia',
 'Alesia',
 'Alessandro',
 'Alessandro',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alex',
 'Alexa',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexander',
 'Alexandra',
 'Alexandra',
 'Alexandra',
 'Alexandre',
 'Alexia',
 'Alexis',
 'Alexis',
 'Alf',
 'Alf',
 'Alford',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfred',
 'Alfredo',
 'Ali',
 'Ali',
 'Alice',
 'Alice',
 'Alice',
 'Alice',
 'Alice',
 'Alice',
 'Alicia',
 'Alicia',
 'Alicia',
 'Aline',
 'Alisa',
 'Alisa',
 'Alison',
 'Alison',
 'Alison',
 'Alison',
 'Alison',
 'Alison',
 'Alison',
 'Alissa',
 'Alissa',
 'Alistair',
 'Alister',
 'Alivia',
 'Alix',
 'Alix',
 'Allain',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allan',
 'Allegra',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allen',
 'Allette',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allison',
 'Allyson',
 'Alma',
 'Almis',
 'Alok',
 'Alphonso',
 'Altagracia',
 'Altom',
 'Alton',
 'Alton',
 'Alton',
 'Alton',
 'Alton',
 'Alvand',
 'Alvarene',
 'Alvaro',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alvin',
 'Alwyn',
 'Alyse',
 'Alyson',
 'Alyson',
 'Alyssa',
 'Alyssa',
 'Alyssa',
 'Alyssa',
 'Amala',
 'Amalia',
 'Aman',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amar',
 'Amarante',
 'Ambar',
 'Amber',
 'Amber',
 'Amber',
 'Ameli',
 'Amelia',
 'Americo',
 'Amiee',
 'Amir',
 'Amit',
 'Ammar',
 'Amme',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Amy',
 'Ana',
 'Ana',
 'Ana',
 'Ana',
 'Ana',
 'Ana',
 'Ana',
 'Ana',
 'Analisa',
 'Anand',
 'Anat',
 'Anatta',
 'Ancil',
 'Anderson',
 'Anderson',
 'Andis',
 'Andre',
 'AnDre',
 'Andre',
 'Andre',
 'Andre',
 'Andre',
 'Andre',
 'Andre',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andres',
 'Andres',
 'Andres',
 'Andres',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrew',
 'Andrewe',
 'Andy',
 'Andy',
 'Andy',
 'Andy',
 'Andy',
 'Andy',
 'Angel',
 'Angel',
 'Angel',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angela',
 'Angelica',
 'Angelica',
 'Angelita',
 'Angelo',
 'Angelo',
 'Angelo',
 'Angelo',
 'Angelo',
 'Angelo',
 'Angelo',
 'Angelyn',
 'Angus',
 'Ani',
 'Ani',
 'Anil',
 'Anita',
 'Anita',
 'Anita',
 'Anita',
 'Anita',
 'Anita',
 'Anita',
 'Anita',
 'Anjan',
 'Ankesh',
 'AnnMargaret',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'Ann',
 'AnnaMarie',
 'Anna',
 'Anna',
 'Anna',
 'Anna',
 'Anna',
 'Anna',
 'Anna',
 'Anna',
 'Annalisa',
 'Annamarie',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 'Anne',
 ...]

In [48]:
len(first_name_list)

26011

In [49]:
df.insert(1, 'first name', first_name_list)
df.insert(1, 'surname', last_name_list)
df['state'] = df['state'].apply(lambda x: x.lower())
df.drop(df[df['state'] == 'no data'].index, inplace = True)
df = df.rename(columns={"fips": "county"})

In [50]:
df['county'] = df['county'].astype(str)
col_list = ['surname', 'first name', 'name', 'state', 'county']
df = df[col_list]

In [51]:
df.to_csv('Dec_18_name_zip_fips_state_with_names.csv')
len(df)

25979

In [41]:
df

            surname first name                       name state county
0        Richardson  Allsbrook     A Allsbrook Richardson    sc    033
1            Turner  Elizabeth         A Elizabeth Turner    ca    037
2           Wambach                           A J Wambach    mn    029
3           Guarino     Joseph           A Joseph Guarino    nj    029
4           Orederu    Omotayo          A Omotayo Orederu    ny    085
5             Comba   Randolph           A Randolph Comba    il    011
6         MacDonald      Blake         A. Blake MacDonald    mn    137
7             Banks     Bowdre        A. Bowdre Banks Jr.    la    071
8         Tomlinson      Bryan         A. Bryan Tomlinson    pa    101
9            Cherry     Collin  A. Collin Cherry, Esquire    fl    073
10          Purcell      Craig           A. Craig Purcell    ny    103
11            Fawal      David             A. David Fawal    al    073
12            Hayes       Dawn              A. Dawn Hayes    fl    057
13             Hood     Dwight             A. Dwight Hood    ms    089
14            Ramos    Gregory           A. Gregory Ramos    tn    037
15        Mastracci        Gus           A. Gus Mastracci    fl    069
16             Datz     Harold             A. Harold Datz    pa    101
17         Williams     Howard         A. Howard Williams    in    141
18         Williams     Stacey      A. I. Stacey Williams    la    071
19            Balbo                     A. J. Balbo, Esq.    ga    029
20           Hinton       Jack             A. Jack Hinton    ga    121
21            Leeds      James             A. James Leeds    ca    037
22             Kemp       Jeff               A. Jeff Kemp    tx    339
23             Tonn      Lance              A. Lance Tonn    mt    017
24          Benassi        Lou             A. Lou Benassi    il    143
25        Martinson        Mac           A. Mac Martinson    al    089
26              Bey      Major               A. Major Bey    pa    101
27         Danovich       Mark         A. Mark O Danovich    il    031
28             Nalu    Michael            A. Michael Nalu    ca    073
29           Dilley     Newton           A. Newton Dilley    mi    081
...             ...        ...                        ...   ...    ...
25949        Priebe    Zachary          Zachary C. Priebe    ia    153
25950        Kelson    Zachary          Zachary D. Kelson    ny    105
25951        Pelham    Zachary          Zachary E. Pelham    nd    015
25952         Cohen    Zachary           Zachary J. Cohen    pa    077
25953       Kansler    Zachary         Zachary J. Kansler    pa    129
25954          Jett    Zachary               Zachary Jett    nc    119
25955       Peagler    Zachary     Zachary Joseph Peagler    al    073
25956        Lemley    Zachary             Zachary Lemley    ca    073
25957        Bravos    Zachary          Zachary M. Bravos    il    043
25958        Cantor    Zachary     Zachary Michael Cantor    ca    037
25959  Christiansen    Zachary    Zachary R. Christiansen    la    071
25960      Scribner    Zachary        Zachary R. Scribner    ca    081
25961     Rozenberg    Zachary          Zachary Rozenberg    ny    047
25962       Schmoll    Zachary            Zachary Schmoll    mn    053
25963      Williams    Zachary        Zachary T. Williams    in    157
25964       VanDyke    Zachary            Zachary VanDyke    fl    005
25965    Greenamyre       Zack         Zack W. Greenamyre    ga    121
25966         Kelin   Zackeree        Zackeree Sean Kelin    nm    001
25967        Hilton       Zane        Zane E Hilton, Esq.    ca    067
25968       Frisbie       Zane               Zane Frisbie    tx    085
25969         Cagle       Zane              Zane T. Cagle    mo    510
25970      Zeringue       Zara              Zara Zeringue    la    103
25971        Snyder    Zebulan          Zebulan P. Snyder    md    510
25972        Wagner    Zebulon          Zebulon N. Wagner    oh    091
25973        Little    Zebulon      Zebulon Peyton Little    al    043
25974     Goldstein        Zev              Zev Goldstein    ny    087
25975    Littlepage        Zoe          Zoe B. Littlepage    tx    201
25976         Silva      Zoilo             Zoilo I. Silva    ny    061
25977        Waters     Zondra        Zondra Hutto Waters    al    125
25978    Manjencich       Zora            Zora Manjencich    az    013

[25947 rows x 5 columns]